spring.application.name=Trabalho-Final-API-

spring.datasource.url=jdbc:h2:mem:Trabalho-Final-API-
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.profiles.active=dev
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USUARIO_EMAIL}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
